///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OnboardingQuestionsModelDataQuestionsOptions {
/*
{
  "id": 17,
  "question_id": 3,
  "is_why": false,
  "label": "Communicates openly",
  "score": 10,
  "image_url": "avatars/50049bdd-6bdf-417a-927d-7419ee208f0d-1753183520105-Rectangle_34625583.png",
  "created_at": "2025-07-22T06:50:52.149Z",
  "updated_at": "2025-07-22T06:50:52.149Z"
}
*/

  int? id;
  int? questionId;
  bool? isWhy;
  String? label;
  int? score;
  String? imageUrl;
  String? createdAt;
  String? updatedAt;

  OnboardingQuestionsModelDataQuestionsOptions({
    this.id,
    this.questionId,
    this.isWhy,
    this.label,
    this.score,
    this.imageUrl,
    this.createdAt,
    this.updatedAt,
  });
  OnboardingQuestionsModelDataQuestionsOptions.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    questionId = json['question_id']?.toInt();
    isWhy = json['is_why'];
    label = json['label']?.toString();
    score = json['score']?.toInt();
    imageUrl = json['image_url']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['question_id'] = questionId;
    data['is_why'] = isWhy;
    data['label'] = label;
    data['score'] = score;
    data['image_url'] = imageUrl;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class OnboardingQuestionsModelDataQuestionsCategory {
/*
{
  "id": 4,
  "label": "Emotional Needs",
  "type": "BARE_MINIMUM"
}
*/

  int? id;
  String? label;
  String? type;

  OnboardingQuestionsModelDataQuestionsCategory({
    this.id,
    this.label,
    this.type,
  });
  OnboardingQuestionsModelDataQuestionsCategory.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    label = json['label']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['label'] = label;
    data['type'] = type;
    return data;
  }
}

class OnboardingQuestionsModelDataQuestions {
/*
{
  "question_id": 3,
  "question": "You need a partner who",
  "category": {
    "id": 4,
    "label": "Emotional Needs",
    "type": "BARE_MINIMUM"
  },
  "options": [
    {
      "id": 17,
      "question_id": 3,
      "is_why": false,
      "label": "Communicates openly",
      "score": 10,
      "image_url": "avatars/50049bdd-6bdf-417a-927d-7419ee208f0d-1753183520105-Rectangle_34625583.png",
      "created_at": "2025-07-22T06:50:52.149Z",
      "updated_at": "2025-07-22T06:50:52.149Z"
    }
  ],
  "user_answer": null
}
*/

  int? questionId;
  String? question;
  OnboardingQuestionsModelDataQuestionsCategory? category;
  List<OnboardingQuestionsModelDataQuestionsOptions?>? options;
  String? userAnswer;

  OnboardingQuestionsModelDataQuestions({
    this.questionId,
    this.question,
    this.category,
    this.options,
    this.userAnswer,
  });
  OnboardingQuestionsModelDataQuestions.fromJson(Map<String, dynamic> json) {
    questionId = json['question_id']?.toInt();
    question = json['question']?.toString();
    category = (json['category'] != null) ? OnboardingQuestionsModelDataQuestionsCategory.fromJson(json['category']) : null;
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <OnboardingQuestionsModelDataQuestionsOptions>[];
      v.forEach((v) {
        arr0.add(OnboardingQuestionsModelDataQuestionsOptions.fromJson(v));
      });
      options = arr0;
    }
    userAnswer = json['user_answer']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['question_id'] = questionId;
    data['question'] = question;
    if (category != null) {
      data['category'] = category!.toJson();
    }
    if (options != null) {
      final v = options;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['options'] = arr0;
    }
    data['user_answer'] = userAnswer;
    return data;
  }
}

class OnboardingQuestionsModelData {
/*
{
  "questions": [
    {
      "question_id": 3,
      "question": "You need a partner who",
      "category": {
        "id": 4,
        "label": "Emotional Needs",
        "type": "BARE_MINIMUM"
      },
      "options": [
        {
          "id": 17,
          "question_id": 3,
          "is_why": false,
          "label": "Communicates openly",
          "score": 10,
          "image_url": "avatars/50049bdd-6bdf-417a-927d-7419ee208f0d-1753183520105-Rectangle_34625583.png",
          "created_at": "2025-07-22T06:50:52.149Z",
          "updated_at": "2025-07-22T06:50:52.149Z"
        }
      ],
      "user_answer": null
    }
  ]
}
*/

  List<OnboardingQuestionsModelDataQuestions?>? questions;

  OnboardingQuestionsModelData({
    this.questions,
  });
  OnboardingQuestionsModelData.fromJson(Map<String, dynamic> json) {
    if (json['questions'] != null) {
      final v = json['questions'];
      final arr0 = <OnboardingQuestionsModelDataQuestions>[];
      v.forEach((v) {
        arr0.add(OnboardingQuestionsModelDataQuestions.fromJson(v));
      });
      questions = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (questions != null) {
      final v = questions;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['questions'] = arr0;
    }
    return data;
  }
}

class OnboardingQuestionsModel {
/*
{
  "status": true,
  "code": "SUCCESS",
  "message": "Fetched bare_minimum successfully.",
  "data": {
    "questions": [
      {
        "question_id": 3,
        "question": "You need a partner who",
        "category": {
          "id": 4,
          "label": "Emotional Needs",
          "type": "BARE_MINIMUM"
        },
        "options": [
          {
            "id": 17,
            "question_id": 3,
            "is_why": false,
            "label": "Communicates openly",
            "score": 10,
            "image_url": "avatars/50049bdd-6bdf-417a-927d-7419ee208f0d-1753183520105-Rectangle_34625583.png",
            "created_at": "2025-07-22T06:50:52.149Z",
            "updated_at": "2025-07-22T06:50:52.149Z"
          }
        ],
        "user_answer": null
      }
    ]
  }
}
*/

  bool? status;
  String? code;
  String? message;
  OnboardingQuestionsModelData? data;

  OnboardingQuestionsModel({
    this.status,
    this.code,
    this.message,
    this.data,
  });
  OnboardingQuestionsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? OnboardingQuestionsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    data['data'] = this.data!.toJson();
      return data;
  }
}
