///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UploadMediaModelData {
/*
{
  "key": "temp/7559fd35-d5ea-4c75-a14c-7ec7b6395833-1752838284659-image_picker_390157E2_8DDA_46EB_9C5E_3C05FCC68382_37539_000044D794CE7ABC.jpg",
  "url": "https://stumbleapps.s3.me-central-1.amazonaws.com/temp/7559fd35-d5ea-4c75-a14c-7ec7b6395833-1752838284659-image_picker_390157E2_8DDA_46EB_9C5E_3C05FCC68382_37539_000044D794CE7ABC.jpg"
}
*/

  String? key;
  String? url;

  UploadMediaModelData({
    this.key,
    this.url,
  });
  UploadMediaModelData.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class UploadMediaModel {
/*
{
  "status": true,
  "code": "SUCCESS",
  "message": "Request was successful.",
  "data": {
    "key": "temp/7559fd35-d5ea-4c75-a14c-7ec7b6395833-1752838284659-image_picker_390157E2_8DDA_46EB_9C5E_3C05FCC68382_37539_000044D794CE7ABC.jpg",
    "url": "https://stumbleapps.s3.me-central-1.amazonaws.com/temp/7559fd35-d5ea-4c75-a14c-7ec7b6395833-1752838284659-image_picker_390157E2_8DDA_46EB_9C5E_3C05FCC68382_37539_000044D794CE7ABC.jpg"
  }
}
*/

  bool? status;
  String? code;
  String? message;
  UploadMediaModelData? data;

  UploadMediaModel({
    this.status,
    this.code,
    this.message,
    this.data,
  });
  UploadMediaModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? UploadMediaModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    data['data'] = this.data!.toJson();
      return data;
  }
}
